version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.14
  build:
    commands:
      - echo Building the Go code...
      - go build application.go
artifacts:
  primary-artifacts:
  secondary-artifacts:
    golang_artifacts:
      base-directory: gitGo
      files:
        - application